# Demystifying ICP Purchasing Power Parity (PPP) Calculations

####  Authors: William Vigil-Oliver and Shriya Chahuan

---
Contents
- [Overview](#Overview) 
- [Load required Python libraries](#Libraries)  
- [Load input data](#InputData) 
- [Calculate basic heading PPPs](#BHPPP)  
- [Calculate above-basic heading PPPs](#aBHPPP)  
---

<a id="Overview"></a>

## Overview
This notebook provides the accompanying code for the World Bank blog "Demystifying ICP Purchasing Power Parity (PPP) Calculations". Its purpose is to lay out the calculation steps and showcase the implementation of the main formulas needed to estimate ICP purchasing power parities (PPPs) at the regional level. The blog post is publicly available [here](http://worldbank.org/xxxxx). 

*Note*: Because the target audience may include users unfamiliar with Python or programming in general, we opted to show each calculation step as explicitly as possible, at the cost of having more modularized and computationally efficient code.

<a id="Libraries"></a>

## Load required Python libraries
The code will require loading the following well-known Python libaries: `pandas`, `numpy` and `statsmodels` 

In [1]:
## Load libaries 
import pandas as pd
import numpy as np 
import statsmodels.api as sm

C:\Users\WB385541\Documents\Tools\Anaconda\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


<a id="InputData"></a>

## Load input data

Let us start by loading input dataset containing mock average price data and other relevant country-level information. 

In [2]:
#Load price data
data="price_data.csv"
prices=pd.read_csv(data) 
prices # Show full dataset 

country       bh      item      price  imp
0   country1  garment  garment1   4500.380  3.0
1   country1  garment  garment2  11583.390  3.0
2   country1  garment  garment3   7000.940  1.0
3   country1     pork     pork1   2500.710  1.0
4   country1     pork     pork2   3561.450  1.0
5   country1     rice     rice1   1020.220  1.0
6   country1     rice     rice2   1000.000  1.0
7   country2  garment  garment1    700.566  1.0
8   country2  garment  garment2    877.950  3.0
9   country2  garment  garment3    616.870  3.0
10  country2     pork     pork1    199.370  3.0
11  country2     pork     pork2    192.910  1.0
12  country2     rice     rice1     70.020  3.0
13  country2     rice     rice2     80.330  1.0
14  country3  garment  garment1  15000.600  3.0
15  country3  garment  garment2  16934.210  1.0
16  country3  garment  garment3   7500.820  1.0
17  country3     pork     pork1   3451.150  3.0
18  country3     pork     pork2        NaN  NaN
19  country3     rice     rice1    780.000  3.0
20  country3     rice     rice2    728.480  3.0
21  country4  garment  garment1        NaN  NaN
22  country4  garment  garment2     88.930  1.0
23  country4  garment  garment3     55.700  3.0
24  country4     pork     pork1     15.250  3.0
25  country4     pork     pork2     30.540  1.0
26  country4     rice     rice1      5.100  3.0
27  country4     rice     rice2      4.250  1.0

This mock dataset contains four countries ('country') and three basic headings ('bh'): garment, rice and pork. Each basic heading contains different varieties of garment, rice and pork. These varieties are contained in the column 'item'. Finally, an average price in local curreny unit is reported for each item ('price') and information on the relative importance of each item in a country’s consumption at the basic heading level is contained in the importance column ('imp'). The ICP Technical Advisory Group (TAG) recommended that a weight of '3' be attached to items identified as 'important' and a weight of '1' to items deemed unimportant.

Notice that the number of item per basic headings varies from three (in the case of garments) to two (rice and pork). This should not be a problem and is common ocurrence in the ICP as basic headings vary in terms of the number of items they contain. Also, notice that not all countries report prices for all items. Again, this a common situation in the actual ICP as not all items can be found or are priced in all countries.

<a id="BHPPP"></a>

## Calculate basic heading PPPs

At the first stage, PPPs are first estimated for more than one hundred groups containing similar items. These groups are called 'basic headings' in the ICP literature. The basic heading is also the level of aggregation for which national accounts expenditure values can typically be provided by ICP-participating countries (which is rarely possible at, say, the item-level). The end-result of this first calculation stage are a set of several PPPs per country, one PPP for each basic heading per country.

The estimation procedure involves averaging price relatives for individual items from different countries within each basic heading to obtain basic heading level PPPs. This is done via a regression method known as the weighted country product dummy (CPD-W). 

The CPD-W is carried out within each basic heading by regressing the logarithm of the observed country item prices on item dummies (one for each item) and country dummies (one for each country other than the numeraire). The CPD-W method also incorporates information on the relative importance of each item in a country’s consumption. Information about the relative importance of each item is reported by each ICP participating country. 

###  Select the numeraire
This refers to the currrency against which all the estimated PPP values will be compared. In the case of the global PPP results, the numeraire would be the US dollar. In this case, we select the currency of 'country2' as the numeraire.

In [3]:
## Select the reference or numeraire currency
numeraire = 'country2' 

###  Prep the inputs to run the CPD-W

In [4]:
## Prep
## Drop country-item observations without a price
prices = prices[prices['price'].notnull()]

## Dataframe with country prices
d_country=pd.get_dummies(prices['country'])

## Prepare design matrix for CPD-W
d_country=pd.get_dummies(prices['country'])
d_country.drop(numeraire, axis=1, inplace=True) #drop numeraire
d_country = d_country.add_prefix('c_') #add prefix to countries
d_item=pd.get_dummies(prices['item'],drop_first=False) #include all item dummies
d_item = d_item.add_prefix('i_') #add prefix to items
prices=pd.concat([prices,d_country,d_item],axis=1) # Concatenate the new cols

## Create empty arrays to store results
l_coef= [] # to store exp(beta_hats)
l_bh= [] # to store bh labels


###  Run the CPD-W on each basic heading and store results

In [5]:
for bh in prices.bh.unique():
    tempdf=prices[prices.bh == bh] 
    X=tempdf.loc[:, [x for x in tempdf.columns if x.startswith(('c_', 'i_'))]]
    y = np.log(tempdf['price']) 
    wts=tempdf['imp']

    wts_cpd=sm.WLS(y, X,weights=wts)
    res=wts_cpd.fit()
    res_eparams=np.exp(res.params)
    
    print("\n","Basic Heading:", bh, "\n")
    print('Exponentiated Parameters:',"\n",
          res_eparams)
    
    l_coef.append(res_eparams)
    l_bh.append(bh)

coef = np.array(l_coef, dtype=float)
coef = np.round(coef,4) # round to 4 decimals
cols = list(X) #store column heads of X as a list
coef[coef == 1] = np.nan #%% replace PPPs that were exp(0)=1 with 'np.nan'


 Basic Heading: garment 

Exponentiated Parameters: 
 c_country1      9.743516
c_country3     20.360644
c_country4      0.094657
i_garment1    598.805582
i_garment2    985.325043
i_garment3    579.168568
i_pork1         1.000000
i_pork2         1.000000
i_rice1         1.000000
i_rice2         1.000000
dtype: float64

 Basic Heading: pork 

Exponentiated Parameters: 
 c_country1     13.874905
c_country3     18.985054
c_country4      0.091746
i_garment1      1.000000
i_garment2      1.000000
i_garment3      1.000000
i_pork1       181.782469
i_pork2       254.494367
i_rice1         1.000000
i_rice2         1.000000
dtype: float64

 Basic Heading: rice 

Exponentiated Parameters: 
 c_country1    14.084683
c_country3    10.511296
c_country4     0.067242
i_garment1     1.000000
i_garment2     1.000000
i_garment3     1.000000
i_pork1        1.000000
i_pork2        1.000000
i_rice1       73.227162
i_rice2       70.230777
dtype: float64


The results above show the estimated coefficients from the CPD-W method for each of the three basic headings. Of particular interest are the estimated coefficients on the country dummies (denoted by the prefix 'c_') as they are the natural log of the estimated country PPP for the basic heading in question. Note that the estimated coefficients have already been exponentiated.

###  Gather and display the estimated basic heading PPPs 

In [6]:
#Create dataframe of PPP results from numpy arrays
#dimension = "# BHs" x "# coef"
df_bhppp=pd.DataFrame(data = coef, index = l_bh, columns = cols)
c_numeraire=f"c_{numeraire}"
df_bhppp.insert(0, c_numeraire, 1.000) #insert column of 1s for numeraire

df_bhppp=df_bhppp.loc[:, [x for x in df_bhppp.columns if x.startswith(('c_'))]] #subsetting to store only country level PPPs
df_bhppp.columns = df_bhppp.columns.str.replace('^c_', '') 

#Column sorting function
def sorting(first_col, df):
    columns = df.columns.tolist()
    columns.remove(first_col)
    columns.insert(0,first_col)
    return df.reindex(columns, axis=1)

#Sort cols with numeraire as col1
sorting(numeraire,df_bhppp)

print("\n","Basic Heading PPPs","\n")
print(df_bhppp, "\n")


 Basic Heading PPPs 

         country2  country1  country3  country4
garment       1.0    9.7435   20.3606    0.0947
pork          1.0   13.8749   18.9851    0.0917
rice          1.0   14.0847   10.5113    0.0672 



<a id="aBHPPP"></a>

## Calculate above-basic heading PPPs

At the second stage of calculation, PPPs estimated at the basic heading level are aggregated using national accounts expenditures values in local currency for each country as weights.

The aggregation method involves constructing bilateral PPPs for each pair of countries, using basic heading level national accounts expenditure values as weights from each country in turn. First, a Laspeyres-type bilateral PPP is calculated between each pair of countries, then a Paasche-type bilateral PPP and finally a Fisher-type bilateral PPP. As a last step, the matrix of Fisher-type bilateral PPPs is made transitive using the Gini-Éltető-Köves-Szulc (GEKS) approach to arrive at a final vector of above basic headings PPPs, containing one PPP for each country relative to the numeraire.

###  Load and display basic heading expenditure values
As a first step let us load the basic heading level national accounts expenditure values in local currency unit for each country.

In [7]:
#Load basic heading expenditure values
#Should contain bh and countries with prefix c
code="bhdata_exp.csv"
df_bh=pd.read_csv(code,index_col="icp_bh")

In [8]:
#Sort cols with numeraire as col1
def sorting(first_col, df):
    columns = df.columns.tolist()
    columns.remove(first_col)
    columns.insert(0,first_col)
    return df.reindex(columns, axis=1)

df_bhexp=sorting(c_numeraire,df_bh)

print("\n","Basic Heading Expenditure Values in Local Currency Units","\n")
print(df_bhexp, "\n")


 Basic Heading Expenditure Values in Local Currency Units 

           c_country2    c_country1    c_country3  c_country4
icp_bh                                                       
rice     2.120000e+12  1.205536e+10  1.945658e+10  6900940414
beef     1.971454e+10  8.160799e+10  2.768787e+10  7189988899
garment  1.270000e+12  7.108761e+08  1.000000e+11  1446676800 



###  Check the basic heading PPP and basic heading expenditure matrices
Before proceeding, it is important to check that both the basic heading PPP and basic heading expenditure matrices have the same dimensions. It is also important to check that the matrix of basic heading PPPs is complete. If the dimensions of the two matrices do not match or the basic heading PPP matrix is incomplete then aggregation at higher aggregate levels is not possible using the formulas employed by the ICP. 

In [9]:
df_bhexp.columns = df_bhexp.columns.str.replace('^c_', '') 

print("Dimensions of Matrices (no. of headings x no. of countries):","\n")
print("BH Purchasing Power Parities (PPPs)  = ",df_bhppp.shape)
print("BH Nominal Expenditures in LCUs      = ", df_bhexp.shape)

Dimensions of Matrices (no. of headings x no. of countries): 

BH Purchasing Power Parities (PPPs)  =  (3, 4)
BH Nominal Expenditures in LCUs      =  (3, 4)


Both matrices have the same dimensions and basic heading PPP matrix is complete, so let us proceed.

###  Calculate bilateral PPPs (Laspeyres-, Paasche-, and Fisher-type)


Laspeyres-type bilateral PPPs

In [10]:
#Calculate Laspeyres bilateral ppps 
shape = (len(df_bhexp.columns),len(df_bhexp.columns))
lp = np.zeros(shape) #square matrix: country x country
nrow= len(lp)  # gets the number of rows
ncol = len(lp[0]) #get the number of cols

for row in range(nrow):
    for col in range(ncol):
        #weighted means by looping over df rows
        lp[row][col]= np.average((df_bhppp.iloc[:,row]/df_bhppp.iloc[:,col]),weights=df_bhexp.iloc[:,col])

lp_ppp = lp

Square ('country x country') matrix of bilateral (Laspeyres-type) PPPs

In [11]:
print("Laspeyres-type bilateral PPPs:","\n", lp_ppp)

Laspeyres-type bilateral PPPs: 
 [[1.00000000e+00 7.59682297e-02 8.10602828e-02 1.11218715e+01]
 [1.13843332e+01 1.00000000e+00 1.11143732e+00 1.35229214e+02]
 [1.66841256e+01 1.45576582e+00 1.00000000e+00 2.05860193e+02]
 [8.44398614e-02 6.99251485e-03 5.86867217e-03 1.00000000e+00]]


Paasche-type bilateral PPPs

In [12]:
#Calculate Paasche bilateral ppps 
pa_ppp = np.transpose(np.reciprocal(lp_ppp))


Square ('country x country') matrix of bilateral (Paasche-type) PPPs

In [13]:
print("Paasche-type bilateral PPPs:","\n", pa_ppp)

Paasche-type bilateral PPPs: 
 [[1.00000000e+00 8.78400155e-02 5.99372137e-02 1.18427480e+01]
 [1.31633974e+01 1.00000000e+00 6.86923671e-01 1.43010065e+02]
 [1.23364978e+01 8.99735844e-01 1.00000000e+00 1.70396296e+02]
 [8.99129254e-02 7.39485183e-03 4.85766570e-03 1.00000000e+00]]


Fisher-type bilateral PPPs by taking the geometric mean of the Laspeyres-type PPP
and the Paasche-type PPP for the aggregate

In [14]:
#Create geomean function
def nangmean(arr, axis=None):
    arr = np.asarray(arr)
    inverse_valids = 1. / np.sum(~np.isnan(arr), axis=axis)  # could be a problem for all-nan-axis
    rhs = inverse_valids * np.nansum(np.log(arr), axis=axis)
    return np.exp(rhs)

#Calculate Fisher bilateral ppps 
fi = np.zeros(shape)
nrow=len(fi)
ncol=len(fi[0])

for row in range(nrow):
    for col in range(ncol):
        fi[row][col]= nangmean([lp_ppp[row][col],pa_ppp[row][col]])
        
fi_ppp = fi

Square ('country x country') matrix of bilateral (Fisher-type) PPPs

In [15]:
print("Fisher-type bilateral PPPs:","\n", fi_ppp)

Fisher-type bilateral PPPs: 
 [[1.00000000e+00 8.16887414e-02 6.97031383e-02 1.14766511e+01]
 [1.22415890e+01 1.00000000e+00 8.73769196e-01 1.39065232e+02]
 [1.43465563e+01 1.14446699e+00 1.00000000e+00 1.87290722e+02]
 [8.71334320e-02 7.19086999e-03 5.33929279e-03 1.00000000e+00]]


###  Calculate GEKS PPPs

Finally, let us calculate the GEKS PPPs between each country and the numeraire. The GEKS PPPs for country with respect to the numeraire is given by the geometric mean of the Fisher-type PPP relatives between each pair of countries and the remaining countries. The result is not a matrix of bilateral PPPs but, instead, a vector of PPPs (one PPP per country). 

This vector of PPPs is referred to as 'multilateral PPPs' because the GEKS procedure takes into account the relative prices between all of the countries as a group. The GEKS is needed to make the Fisher-type bilateral PPPs transitive and base country–invariant. Transitivity simply means that the PPP between any two countries should be the same whether it is computed directly or indirectly through a third country (like with market exchange rates). Base country–invariant means that the PPPs between any two countries should be the same regardless of the choice of base country.

In [16]:
#Calculate GEKS multilateral ppps 
##reqs the earlier nangmean function 
geks = np.zeros(shape)  # zero 'country x country' matrix
nrow=len(geks)  # gets the number of rows
ncol=len(geks[0])

for row in range(nrow):
    for col in range(ncol):
        geks[row][col]= nangmean(fi_ppp[row]/fi_ppp[col])     

geks_vec = np.zeros(shape=(1,len(df_bhexp.columns))) # as we need a vector of ppps, not a matrix
j=len(geks_vec[0])
for col in range(j):#..one PPP per country, or col of bhexp df
    geks_vec[:,col]=nangmean(geks[col,0]/geks[0,0]) #geomean over each row, w/ each col rebased to country in col1    

geks_ppp = np.array(geks_vec)
geks_ppp = np.round(geks_ppp,4) # round to 4 decimals

Display the estimated vector of GEKS PPPs, containing one above-basic heading multilateral PPP per country.

In [17]:
geks_ppp = pd.DataFrame(geks_ppp)
geks_ppp.columns = df_bhexp.columns
geks_ppp = round(geks_ppp,4)

print("\n","GEKS Multilateral PPPs","\n")
print(geks_ppp, "\n")


 GEKS Multilateral PPPs 

   country2  country1  country3  country4
0       1.0    12.283   14.7285    0.0846 

